package compose

import (
	"bytes"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/nicolaeser/HermesManager/internal/config"
	"github.com/nicolaeser/HermesManager/internal/fsutil"
	"github.com/nicolaeser/HermesManager/internal/secrets"
	"github.com/nicolaeser/HermesManager/internal/stack"
)

type Generator struct {
	Paths stack.Paths
}

func (generator Generator) Prepare(cfg config.Config, secretValues secrets.Values) error {
	if err := cfg.Validate(); err != nil {
		return err
	}
	for _, key := range []string{
		secrets.DashboardUsername,
		secrets.DashboardPassword,
		secrets.DashboardSecret,
	} {
		if secretValues[key] == "" {
			return fmt.Errorf("required dashboard credential %s is missing", key)
		}
	}

	for _, directory := range []struct {
		path string
		mode os.FileMode
	}{
		{generator.Paths.Manager, 0o700},
		{generator.Paths.Data, 0o700},
		{generator.Paths.Workspace, 0o755},
		{generator.Paths.Backups, 0o700},
	} {
		if err := ensureDirectory(directory.path, directory.mode); err != nil {
			return err
		}
	}

	content := Render(cfg, generator.Paths)
	existing, err := os.ReadFile(generator.Paths.Compose)
	if err == nil && bytes.Equal(existing, content) {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read Compose file: %w", err)
	}
	if err := fsutil.AtomicWriteFile(generator.Paths.Compose, content, 0o600); err != nil {
		return fmt.Errorf("write Compose file: %w", err)
	}
	return nil
}

func Render(cfg config.Config, paths stack.Paths) []byte {
	var output strings.Builder
	fmt.Fprintf(&output, "# Generated by Hermes Manager. Re-run install to repair this file.\n")
	fmt.Fprintf(&output, "#\n")
	fmt.Fprintf(&output, "# Persistence (survives image update / container recreate):\n")
	fmt.Fprintf(&output, "#   data/      → /opt/data   = Hermes HERMES_HOME (config, sessions, memories,\n")
	fmt.Fprintf(&output, "#                              and Hermes' own data/workspace). THIS is the critical store.\n")
	fmt.Fprintf(&output, "#   workspace/ → /workspace  = optional host project files (NOT Hermes core state).\n")
	fmt.Fprintf(&output, "#   backups/   → /backups    = hermes backup/import archives on the host.\n")
	fmt.Fprintf(&output, "# The manager never runs \"down -v\" and never deletes these host directories on update.\n")
	fmt.Fprintf(&output, "name: %s\n\n", yamlQuote(cfg.Name))
	output.WriteString("services:\n")
	output.WriteString("  hermes:\n")
	fmt.Fprintf(&output, "    image: %s\n", yamlQuote(cfg.EffectiveImage()))
	fmt.Fprintf(&output, "    container_name: %s\n", yamlQuote(cfg.Name))
	output.WriteString("    restart: unless-stopped\n")
	output.WriteString("    command: [\"gateway\", \"run\"]\n")
	output.WriteString("    working_dir: /workspace\n")
	output.WriteString("    stop_grace_period: 1m\n")
	output.WriteString("    env_file:\n")
	output.WriteString("      - ./.manager/secrets.env\n")
	output.WriteString("    environment:\n")
	fmt.Fprintf(&output, "      HERMES_UID: %s\n", yamlQuote(strconv.Itoa(os.Getuid())))
	fmt.Fprintf(&output, "      HERMES_GID: %s\n", yamlQuote(strconv.Itoa(os.Getgid())))
	// Explicit for clarity; the image defaults match these values.
	output.WriteString("      HERMES_HOME: \"/opt/data\"\n")
	output.WriteString("      HERMES_WRITE_SAFE_ROOT: \"/opt/data\"\n")
	output.WriteString("      HERMES_DASHBOARD: \"1\"\n")
	output.WriteString("      HERMES_DASHBOARD_HOST: \"0.0.0.0\"\n")
	output.WriteString("      HERMES_DASHBOARD_PORT: \"9119\"\n")
	output.WriteString("      HERMES_GATEWAY_BOOTSTRAP_STATE: \"running\"\n")
	output.WriteString("    ports:\n")
	fmt.Fprintf(&output, "      - %s\n", yamlQuote(fmt.Sprintf("%s:%d:9119", cfg.BindAddress, cfg.DashboardPort)))
	fmt.Fprintf(&output, "      - %s\n", yamlQuote(fmt.Sprintf("%s:%d:8642", cfg.BindAddress, cfg.APIPort)))
	output.WriteString("    extra_hosts:\n")
	output.WriteString("      - \"host.docker.internal:host-gateway\"\n")
	output.WriteString("    volumes:\n")
	writeBind(&output, paths.Data, "/opt/data")
	writeBind(&output, paths.Workspace, "/workspace")
	writeBind(&output, paths.Backups, "/backups")
	output.WriteString("    healthcheck:\n")
	output.WriteString("      test: [\"CMD\", \"python\", \"-c\", \"import json,urllib.request; d=json.load(urllib.request.urlopen('http://127.0.0.1:9119/api/health',timeout=3)); assert d.get('ok') and d.get('auth_required')\"]\n")
	output.WriteString("      interval: 30s\n")
	output.WriteString("      timeout: 5s\n")
	output.WriteString("      retries: 3\n")
	output.WriteString("      start_period: 45s\n")
	output.WriteString("    logging:\n")
	output.WriteString("      driver: json-file\n")
	output.WriteString("      options:\n")
	output.WriteString("        max-size: \"10m\"\n")
	output.WriteString("        max-file: \"3\"\n")
	output.WriteString("    labels:\n")
	output.WriteString("      io.hermes-manager.managed: \"true\"\n")
	fmt.Fprintf(&output, "      io.hermes-manager.schema: %s\n", yamlQuote(strconv.Itoa(config.SchemaVersion)))
	return []byte(output.String())
}

func writeBind(output *strings.Builder, source, target string) {
	output.WriteString("      - type: bind\n")
	fmt.Fprintf(output, "        source: %s\n", yamlQuote(source))
	fmt.Fprintf(output, "        target: %s\n", yamlQuote(target))
	output.WriteString("        bind:\n")
	output.WriteString("          create_host_path: false\n")
}

func ensureDirectory(path string, mode os.FileMode) error {
	info, err := os.Stat(path)
	if err == nil {
		if !info.IsDir() {
			return fmt.Errorf("%s exists but is not a directory", path)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("inspect %s: %w", path, err)
	}
	if err := os.MkdirAll(path, mode); err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	if err := os.Chmod(path, mode); err != nil {
		return fmt.Errorf("set permissions on %s: %w", path, err)
	}
	return nil
}

func yamlQuote(value string) string {
	return strconv.Quote(value)
}
