package secrets

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/nicolaeser/HermesManager/internal/fsutil"
	"github.com/nicolaeser/HermesManager/internal/stack"
)

const (
	DashboardUsername = "HERMES_DASHBOARD_BASIC_AUTH_USERNAME"
	DashboardPassword = "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD"
	DashboardSecret   = "HERMES_DASHBOARD_BASIC_AUTH_SECRET"
)

type Store struct {
	Paths stack.Paths
}

type Values map[string]string

func (s Store) LoadOrCreate(username string) (Values, bool, error) {
	values, err := s.Load()
	created := false
	if err != nil {
		if !os.IsNotExist(unwrapPathError(err)) {
			return nil, false, err
		}
		values = Values{}
		created = true
	}
	changed, err := ensureRequired(values, username)
	if err != nil {
		return nil, false, err
	}
	if created || changed {
		if err := s.Save(values); err != nil {
			return nil, false, err
		}
	}
	return values, created, nil
}

func (s Store) Load() (Values, error) {
	file, err := os.Open(s.Paths.Secrets)
	if err != nil {
		return nil, fmt.Errorf("open dashboard credentials: %w", err)
	}
	defer file.Close()

	values := Values{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, found := strings.Cut(line, "=")
		if !found || strings.TrimSpace(key) == "" {
			return nil, fmt.Errorf("invalid credentials line: %q", line)
		}
		values[strings.TrimSpace(key)] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read dashboard credentials: %w", err)
	}
	return values, nil
}

func (s Store) Save(values Values) error {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var content strings.Builder
	content.WriteString("# Generated by Hermes Manager. Keep this file private.\n")
	for _, key := range keys {
		value := values[key]
		if strings.ContainsAny(key+value, "\r\n\x00") || strings.Contains(key, "=") {
			return fmt.Errorf("credential %s is not a single-line env value", key)
		}
		fmt.Fprintf(&content, "%s=%s\n", key, value)
	}
	if err := fsutil.AtomicWriteFile(s.Paths.Secrets, []byte(content.String()), 0o600); err != nil {
		return fmt.Errorf("save dashboard credentials: %w", err)
	}
	return nil
}

func (s Store) RotateDashboard(values Values) (string, error) {
	password, err := randomHex(18)
	if err != nil {
		return "", err
	}
	sessionSecret, err := randomHex(32)
	if err != nil {
		return "", err
	}
	values[DashboardPassword] = password
	values[DashboardSecret] = sessionSecret
	if err := s.Save(values); err != nil {
		return "", err
	}
	return password, nil
}

func ensureRequired(values Values, username string) (bool, error) {
	changed := false
	if values[DashboardUsername] == "" {
		values[DashboardUsername] = username
		changed = true
	}
	for key, bytes := range map[string]int{
		DashboardPassword: 18,
		DashboardSecret:   32,
	} {
		if values[key] != "" {
			continue
		}
		value, err := randomHex(bytes)
		if err != nil {
			return false, err
		}
		values[key] = value
		changed = true
	}
	return changed, nil
}

func randomHex(bytes int) (string, error) {
	buffer := make([]byte, bytes)
	if _, err := rand.Read(buffer); err != nil {
		return "", fmt.Errorf("generate random credential: %w", err)
	}
	return hex.EncodeToString(buffer), nil
}

func unwrapPathError(err error) error {
	for err != nil {
		if pathError, ok := err.(*os.PathError); ok {
			return pathError.Err
		}
		unwrapper, ok := err.(interface{ Unwrap() error })
		if !ok {
			return err
		}
		err = unwrapper.Unwrap()
	}
	return nil
}
